[package]
name = "patio-pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
image = "0.24"

[[bin]]
name = "patio-pi"
path = "src/main.rs"
